#include <iostream>

void testPixelBuffer();
void testRasterizer();
void testFilledTriangle();
void testVec2();
void testVec3();
void testVec4();
void testMat4();
void testClipper();
void testDepthBuffer();
void testTriangleDepth();
void testShading();
void testTransform();
void testObjLoader();
void testObjUvs();
void testGltfLoader();
void testGltfAttributes();
void testGltfTextures();
void testGlbTextures();
void testModelBounds();
void testRay();
void testMoveToController();
void testCharacter();
void testInput();
void testFixedTimestep();
void testSdlInput();
void testWorld();
void testModelRenderer();
void testEdgePan();
void testDemoGame();
void testCameraControllers();
void testAssetManager();

int main(){
    testPixelBuffer();
    testRasterizer();
    testFilledTriangle();
    testVec2();
    testVec3();
    testVec4();
    testMat4();
    testClipper();
    testDepthBuffer();
    testTriangleDepth();
    testShading();
    testTransform();
    testObjLoader();
    testObjUvs();
    testGltfLoader();
    testGltfAttributes();
    testGltfTextures();
    testGlbTextures();
    testModelBounds();
    testRay();
    testMoveToController();
    testCharacter();
    testInput();
    testFixedTimestep();
    testSdlInput();
    testWorld();
    testModelRenderer();
    testEdgePan();
    testDemoGame();
    testCameraControllers();
    testAssetManager();

    std::cout << "All tests passed!\n";
    return 0;
}
